image: ruby:2.5

stages:
  - build
  - deploy

variables:
  JEKYLL_ENV: production

before_script:
  - export LC_ALL="C.UTF-8"
  - export LANG="en_US.UTF-8"
  - export LANGUAGE="en_US.UTF-8"
  - curl -sL https://deb.nodesource.com/setup_8.x | bash
  - apt-get install -y nodejs
  - bundle install

build:
  stage: build
  script:
  - bundle exec jekyll build -d _site
  only:
    - master
  artifacts:
    paths:
    - _site


deploy:
  stage: deploy
  script:
  - apt-get update -qq && apt-get install -y -qq lftp
  - lftp -c "set ftp:ssl-allow yes; open -u $USERNAME,$PASSWORD $HOST; mirror -Rv _site/ /httpdocs/moritz-brunnengraeber/  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
  only:
  - master
