# Site settings
title: Moritz Brunnengräber
description: >- # this means to ignore newlines until "baseurl:"
  Get to know me! I am a master student in Geodesy and Geoinformation and I love modern technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.moritz-brunnengraeber.de/" # the base hostname & protocol for your site, e.g. http://example.com

social_googleplus: https://plus.google.com/+MoritzBrunnengr%C3%A4ber
social_facebook: https://www.facebook.com/moritz.brunnengraeber
social_360cities: https://www.360cities.net/profile/moritzbrunnengraeber
social_sketchfab: https://sketchfab.com/MoritzB
social_mail: mail@moritz-brunnengraeber.de

google_maps_api: AIzaSyDeJbsLO30Ip1EaPqx9HuC363gT2r7WanA

legal_name: Moritz Brunnengräber
legal_address: Münchner Straße 45<br>82178 Puchheim<br>Germany
legal_mail: mail@moritz-brunnengraeber.de

# Make all links pretty ( -> no file extension)
permalink: pretty

sass:
  style: compressed
  sass_dir: css/_scss

plugins:
- jekyll-autoprefixer
