name: Build and deploy to hosting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout latest code
      uses: actions/checkout@v4

    - name: Setup node LTS
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./dist
        server-dir: /httpdocs/moritz-brunnengraeber/
